blank_issues_enabled: false
contact_links:
  - name: Allgemeine Fragen & Support
    url: michael-hamann@outlook.com
    about: Bitte verwenden Sie dieses Formular nur f√ºr technische Fragen oder wenn Sie sich nicht sicher sind, welches Template Sie verwenden sollen.
